### ISSUE TITLE
For the offline mode What are the accepted file formats

### ISSUE THREAD

**Issue by YusufAtes** [muccc/gr-iridium#100]

**Comment by Sec42** [comment]
Offline mode takes raw samples in a lot of formats - see list for the -f option https://github.com/muccc/gr-iridium#-f-input-file-format 

The readme has an example for raw https://github.com/muccc/gr-iridium#offline-raw-capture or a sigmf capture file https://github.com/muccc/gr-iridium#offline-sigmf
