### ISSUE TITLE
IRA Signal

### ISSUE THREAD

**Issue by tk240** [muccc/gr-iridium#107]
I am trying to receive the ring alert signals from iridium satellites using hackrf i couldn't find a way to receive only the ring alert band and when i tried to receive all band with default hackrf config file from gr-iridium i get the following outputs which only few of the signals are okay what should ı do and where could be the problem caused from config file, antenna
![ety8e8x07fc81](https://user-images.githubusercontent.com/79604687/150133572-953efc01-91e3-4b81-b4df-3f98a3b45b7f.png)

**Comment by Sec42** [comment]
I suggest you take a look at the spectrum in a waterfall display to check the quality of your setup.

With a good setup you should be able to clearly see the iridium bursts, similar to https://www.youtube.com/watch?v=YsAn9jpA2Z8

Without seeing your spectrum its hard to tell what the problem could be.

The burst squelch messages may indicate some kind of interference - if you get them continuously & every time you run the extractor.

The reason may be strong transmitters nearby, bad or no filter in the antenna, inadequate shielding on the SDR or antenna cables, etc.
