### ISSUE TITLE
Airspy Bias-T support

### ISSUE THREAD

**Issue by jon38711** [muccc/gr-iridium#16]
I tried adding 'bias=1' in my airspy.conf but it did not work. Is this option being passed into gr-osmosdr?

Thanks.

**Comment by schneider42** [comment]
Have you tried to add `device_args='bias=1'` to the configuration? Maybe it has to be `device_args='airspy=0,bias=1'`, though.

**Comment by n0p** [comment]
Works for me with 
`device_args='airspy=0,bias=1'`

**Comment by schneider42** [comment]
Thanks, I've added this to the example configuration
