### ISSUE TITLE
Implausible signal levels

### ISSUE THREAD

**Issue by Sec42** [muccc/gr-iridium#17]
gr-iridium sometimes outputs an implausible signal level e.g.
RAW: i-1474564631-t1 9738470 1625457152 A:OK I:00029974620  96% 17284762435584.000 179 0011...

**Comment by schneider42** [comment]
This might be related to https://github.com/muccc/gr-iridium/issues/8

**Comment by Sec42** [comment]
This Problem still exists. I am now seeing also "inf" and "nan" as signal level:

```
RAW: i-1569967245-t1 0095370 1622473984 A:OK I:00000329220  97% inf 179 ...
```
and
```
RAW: i-1569967245-t1 9764199 1619392128 A:OK I:00039245121  99% nan 179 ...
```

**Comment by Sec42** [comment]
As far as I can tell this issue has completely disappeared since November.
Closing now, will reopen in case it reappears.
