### ISSUE TITLE
fault during starting gr-iridium.

### ISSUE THREAD

**Issue by Mijntje** [muccc/gr-iridium#177]
Hi,

During starting gr-iridium I've encounter some problems. Yesterday I managed to solve a problem which I've forgot what it actually was something with python.. but I've managed to solve it by using this command: 
export PYTHONPATH=/usr/local/lib/python3.10/site-packages. 

It was already late and stopped trying further. And today is a new fresh day.

But now when I try to start up gr-iridium I'm getting this problem:

`    ~/iridium/gr-iridium/examples    master !1    iridium-extractor -D 4 rtl-sdr.conf | grep "A:OK" > /home/g/iridium/output/output.bits                    ✔ 
Traceback (most recent call last):
  File "/usr/local/bin/iridium-extractor", line 203, in <module>
    center = int(d['center_freq'])
ValueError: invalid literal for int() with base 10: "1625500000\n\n\ndevice_args='rtl=0,bias=1'"
    ~/iridium/gr-iridium/examples    master !1       `

Anyone an idea where too look for?

**Comment by schneider42** [comment]
@Mijntje can you post your rtl-sd.conf here (as attachment)?
