### ISSUE TITLE
Error while running iridium-extractor

### ISSUE THREAD

**Issue by alphapats** [muccc/gr-iridium#179]
I am getting error while running iridium-extractor:-

Traceback (most recent call last):
  File "/usr/local/bin/iridium-extractor", line 10, in <module>
    import iridium.iridium_extractor_flowgraph
ModuleNotFoundError: No module named 'iridium'

Even I am running gnuradio, gr_iridium blocks are not present.

OS: Ubuntu 22.04.2 LTS
gnuradio: GNU Radio Companion 3.10.5.1

**Comment by Sec42** [comment]
This sounds like gr-iridium is not properly installed. Can you share the exact steps you did to install?
