### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by t121028** [muccc/gr-iridium#183]
I downloaded source and try cmake by "cmake -B build" command, but error appears.

Make Error at /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GrPython.cmake:184 (add_custom_target):
  add_custom_target cannot create target "ALL" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/labg580/ドキュメント/gr-iridium-1.0.0/apps".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GrPython.cmake:374 (GR_UNIQUE_TARGET)
  python/CMakeLists.txt:32 (GR_PYTHON_INSTALL)

OS: Ubuntu 22.04.3 LTS
Gnuradio: 3.10.1.1
Python: 3.10.12

**Comment by schneider42** [comment]
Sorry, I can't reproduce this.

My setup:
Ubuntu 22.04.4 LTS
GNURadio 3.10.1.1-2
Python 3.10.12

That is super close to your setup, so I'm not sure why it is failing for you. Can you try again with a fresh clone?
