### ISSUE TITLE
fft_burst_tagger_impl.cc:134:34: error: expected ‘)’ before ‘PRIu64’

### ISSUE THREAD

**Issue by joej** [muccc/gr-iridium#20]
Just cloned current head. I'm in a Centos machine 3.10.0-327 kernel

All C++ references to using PRIu64 to format (inside fprintf, etc) get compiler failures.

My guess ... missing __STDC_FORMAT_MACROS definition somewhere. But then, when I insert that in the lib/*.cc file, the err still shows up. 

- edited tagged_burst, fft_burst, and burst_downmix CC files in lib/ .... make clean && make ... still gives error on the PRIu64 
- specifically defined PRIu64 as 'llu' in fft_burst*cc file, after intttypes include ... STILL fails. I'm starting to think this is NOT a 'definition' problem. 
- I give up. I'm rewriting the fprintf/printf statements to simply use '%llu'

**Comment by schneider42** [comment]
Can you provide some details about your build environment (OS, Compiler, etc.)?

**Comment by schneider42** [comment]
Not heard anything similar again. Please reopen if this still an issue with current OS versions.
