### ISSUE TITLE
lib/test-iridium floating point exception, fails

### ISSUE THREAD

**Issue by joej** [muccc/gr-iridium#21]
cloned gnuradio, current rep head -- built/installed
PYTHONPATH=/usr/local/lib64/python2.7/site-packages   # - to include gnuradion python

cloned gr-iridium repo's current head -- built
make test fails
more detail from _**/usr/bin/ctest -VV --force-new-ctest-process**_ command

it turns out that **_lib/test-iridium_** binary fails with floating point exception and gdb says SIGPE 
Someone dividing by 0 ?

--joe

**Comment by TheBiggerGuy** [comment]
Hi Joe.
I believe I have fixed the issue. Could you please test pull request #29

**Comment by Sec42** [comment]
fix was merged in 2018
