### ISSUE TITLE
voice message and sms not able to decode after output.parsed 

### ISSUE THREAD

**Issue by rinkunamaste** [muccc/gr-iridium#22]
Hello Everyone 
I have received many message from iridium satellite but not able to play using play-iridium-ambe and decode IMS packet in text format. Even if i am running wire-shark command sudo wireshark -k -Y 'gsmtap && !icmp' -i lo, this command is not running at all and no output is visible. I am posting some message which i captured through iridium toolkit.
IMS: i-1487244202-t1 000038402 1626451072  96%   0.002 132 DL 00110011111100110011001111110011 odd:100001                     4:A:06 1 c=02201           00000000 00000000000000000000 00000000000000000000 00000000000000000000 descr_extra:0110101101011110011100110011110001101011
VOC: i-1487751545-t1 000252522 1621335936  97%   0.002 179 DL LCW(0,T:rsrvd,C:<>(48),1048560 E0)                                                                              [49.48.ce.db.82.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.44]
kindly help me what i have to run to get sms and voice using iridium toolkit.
Thanking You

**Comment by Sec42** [comment]
I'm not really sure what you were trying to do. the wireshark commandline you showed is doing a live capture, but nothing in iridium supports that. The reassembler can be used to read a ".parsed" file and produce a pcap file. This can then be opened in wireshark. Check https://github.com/muccc/iridium-toolkit/blob/master/README.md#reassembler for reference.  If you still have problems getting stuff to work, please stop by on IRC or re-open this issue with the commands you were trying to run.
