### ISSUE TITLE
Gnuradio 3.7.5

### ISSUE THREAD

**Issue by audioplatinum** [muccc/gr-iridium#25]
Hi, 
How I can build gr-iridium on Gnuradio 3.7.5 instead 3.7.6? 
I can not update gnuradio 3.7.5, and I am stuck here..is there a possibility to install somehow on 3.7.5?

Regards,
Raf

**Comment by schneider42** [comment]
Without digging deeper: I don't think so. There are a few functions in use which AFAIK were introduces with 3.7.6. I'm sorry.

**Comment by audioplatinum** [comment]
Ok, no problem, thanks for info! 

Cheers, 
Raf
