### ISSUE TITLE
LNA4ALL use?

### ISSUE THREAD

**Issue by dsound** [muccc/gr-iridium#3]
Just wondering if an LNA4ALL is turned on automatically when running extractor or is there a command that could turn it on for extra amplification.

**Comment by undingen** [comment]
you must turn it on by adding `device_args=hackrf=0,bias=1` to your config.
If it worked a message will be print to stderr on startup:
```
Using HackRF One with firmware 2015.07.2 
Enabled antenna bias voltage
```

**Comment by schneider42** [comment]
I've added the line to the hackrf config files (commented).
