### ISSUE TITLE
osmosdr in gr-iridium?

### ISSUE THREAD

**Issue by dougw65** [muccc/gr-iridium#40]
New to linux and trying to run gr-iridium in Skywave Linux. When I try to run the extractor in terminal,I am greeted with this failure message:

dougw65@aa0dw-2:~$ iridium-extractor -D 4 examples/airspy.conf | grep "A:OK" > output.bits
Traceback (most recent call last):
  File "/usr/local/bin/iridium-extractor", line 10, in <module>
    import iridium.iridium_extractor_flowgraph
  File "/usr/local/lib/python2.7/dist-packages/iridium/iridium_extractor_flowgraph.py", line 8, in <module>
    import osmosdr
ImportError: No module named osmosdr

Osmsdr appears to be in the directory but not sure if this is a problem with "osmosdr" or perhaps gnu-radio? 

appreciate any help/guidance

**Comment by schneider42** [comment]
Sorry for replying so late. I don't know which version of GNURadio Skywave Linux is using. Judging by the python version it seems to be pre 3.8, which I consider ancient by now.

Please give a more recent version of your Linux distribution and gr-iridium a try.
