### ISSUE TITLE
Error in '/usr/bin/python2': corrupted double-linked list 0x01292c68

### ISSUE THREAD

**Issue by jbarea** [muccc/gr-iridium#44]
Hello all, just built gr-iridium as per the instruction page. It all went well until when i try to run it, i get the error above. As i have gnuradio 3.7, i switched branch before building, but can't get it to work. I'm using a bladerf. I will keep investigating and post here if i get a solution, in the meantime would like any hint in order to get it running.
Thanks in advance!

**Comment by schneider42** [comment]
The 3.7 branch should be considered legacy. Please open another issue if you see issues on 3.8, 3.9 or 3.10
