### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [muccc/gr-iridium#58]
Hi, can you add the following topics to this repository?
* https://github.com/topics/sdr
* https://github.com/topics/gnu-radio
* https://github.com/topics/gnuradio
* https://github.com/topics/rtl-sdr
* https://github.com/topics/hackrf
* https://github.com/topics/iridium

Thanks!

**Comment by Sec42** [comment]
Finally added some topics. Thanks for the reminder.

**Comment by mendel5** [comment]
Thank you!
