### ISSUE TITLE
Wrong number or type 'new_time_spec_t'

### ISSUE THREAD

**Issue by AdmiralGeta** [muccc/gr-iridium#96]
Hi schneider, i installed Gnuradio3.9 and last gr-iridium from master branch, installation was successful but i have TypeError conflict, can you tell what I did wrong

Setup:
OS: Dragonos\Lubuntu
Receiver`s: limeSDR\RTL-SDR

![LimeBug](https://user-images.githubusercontent.com/32673248/142726261-b122fb5d-998c-43c4-95b8-283522f55136.png)

**Comment by schneider42** [comment]
It looks like gr-osmosdr is installed for gnuradio 3.8 (it mentions SWIG in the traceback). Your system must have a mix of GNURadio 3.9 and GNURadio 3.8. How did you install GNURadio and how did you install gr-osmosdr?

A first tip:
You must _never_ install GNURadio 3.9 from the PPA and then install gr-osmosdr bia apt. It _will_ lead to a broken installation.

**Comment by schneider42** [comment]
@AdmiralGeta Any update on this? Otherwise I'm going to close this issue

**Comment by AdmiralGeta** [comment]
Yes, you can close my issues, I install all instruments, thanks for your
work and help.

Best winches!

сб, 22 січ. 2022 р. о 22:44 schneider42 ***@***.***> пише:
