### ISSUE TITLE
Error: Line 316 Flow Graph

### ISSUE THREAD

**Issue by FairyballYT** [muccc/gr-iridium#98]
Hi, so I tried to run iridium-extractor within a VirtualBox virtual machine running DragonOS Focal Public R18 (which is based off of Debian 20.04) but I kept getting this flow graph error when trying to do an online decode from my RTL-SDR V3 dongle. I compiled/installed GNU-Radio from the 3.9.0.0 source, installed gr-iridium, and while gr-iridium will launch and find my RTL-SDR, it will crash within a few seconds due to this Line 316 Flow Graph Python error. I'm not sure how to resolve the issue, is my copy of gr-iridium missing some python files? Do I need to replace a file within the gr-iridium folder?
![Screenshot 2021-12-08 2 03 am - iridium extractor python flow graph error](https://user-images.githubusercontent.com/81061935/145172019-1f04ca10-3843-499c-809e-a004ae05caf3.png)

**Comment by schneider42** [comment]
The name of the parameter changed from `signal_width` to `burst_width` earlier this year e13828720b2afeaaf0ff14e38e38a1005eb4b4ab

It changed on both sides though. It's almost like you got a new version of one file and an old version of another file on your system.

Can you show us the output of `find /usr -name iridium_extractor_flowgraph.py`? I'm wondering if you have this file twice.

**Comment by FairyballYT** [comment]
It looks like I have the same flowgraph.py file twice. I think DragonOS came preinstalled with Python3, and then either it cane preinstalled with Python3.8 or I tried to install Python 3.8 via the terminal, sorry, foggy memory. ~~Also, I'm not sure if this file is too large, but I would also like to send a copy of some of the programs and libraries that I also tried to install via the terminal.~~
![Screenshot 2021-12-08 2 43 am - Output of command find usr -name iridium_extractor_flowgraph py](https://user-images.githubusercontent.com/81061935/145178272-88b2da5d-d015-4a89-bdee-adf8219bdb3b.png)

**Comment by FairyballYT** [comment]
So I think this was the sequence of installs/events that I performed through the terminal:

1. I both downloaded and installed Volk 2.5 via the terminal.

2. a. I downloaded the source version of GNU Radio 3.9.0.0 from the GNU Radio Wiki, then installed that via the terminal.

2. b. I had to download the library pybind11 off the internet and install that in the terminal otherwise GNU Radio 3.9.0.0 would not install.

3. I download the latest source version of gr-iridium from from 3 days ago off Github and installed it through the terminal.

4. I tried to use the example online command to pull data from my RTL-SDR V3 dongle at 1.622Ghz, but then the flowgraph error appeared.

**Comment by schneider42** [comment]
Is it possible that DragonOS came with an outdated version of gr-iridium pre-installed?

**Comment by FairyballYT** [comment]
> Is it possible that DragonOS came with an outdated version of gr-iridium pre-installed?

No, DragonOS did not come pre installed with gr-iridium at all, I had to download the source code and then install gr-iridium in the terminal.

**Comment by schneider42** [comment]
Can you post the output of `md5sum` for the two files installed?

**Comment by FairyballYT** [comment]
> Can you post the output of `md5sum` for the two files installed?

Sure, the md5sum outputs seem to be different which could indicate that the contents of both flowgraph.py files are different. So... I now have two versions of Python installed in DragonOS? 🤔
![Screenshot 2021-12-08 2 43 am - md5sum (checksum) of 2 flowgraph py files](https://user-images.githubusercontent.com/81061935/145191290-0261a233-cde5-4575-9731-3781f24808b4.png)

**Comment by schneider42** [comment]
This is not a question of which Python versions you have installed. The flowgraph does not come with a Python installation and the Python version does not influence the content of the flowgraph file.

You definitely have two versions of `gr-iridium` on your system though. I don't know how they got there though. Judging from the MD5 sums, one of them is from master (the one in /usr/local/lib/python3.8/dist-packages) and one is from a much earlier version (based on a commit between a7d21a68878989257d99d52481c07ee2d1ce4121..18f7d5b3fc0d1b0de14763eaeb46e15d5db7dba2 from early 2020) in /usr/lib/python3/dist-packages

Either your system came pre installed with a very dated version of gr-iridium or you did install it at some point. I suggest to delete the old version (that includes all the files in `/usr/lib/python3/dist-packages/iridium`).

**Comment by FairyballYT** [comment]
> This is not a question of which Python versions you have installed. The flowgraph does not come with a Python installation and the Python version does not influence the content of the flowgraph file.
> 
> You definitely have two versions of `gr-iridium` on your system. I don't know how they got there though. Judging from the MD5 sums, one of them is from master (the one in /usr/local/lib/python3.8/dist-packages) and one is from a much earlier version (based on a commit between a7d21a68878989257d99d52481c07ee2d1ce4121..18f7d5b3fc0d1b0de14763eaeb46e15d5db7dba2 from early 2020) in /usr/lib/python3/dist-packages
> 
> Either your system came pre installed with a very dated version of gr-iridium or you did install it at some point. I suggest to delete the old version (that includes all the files in `/usr/lib/python3/dist-packages/iridium`).

Oh... I see. How would I delete an old version of a package, just by the package name "python3" in the terminal?

**Comment by FairyballYT** [comment]
Using the command dpkg --list reminded me that DragonOS came preinstalled with... Python 2.7 and Python 3 and Python 3.8?

**Comment by FairyballYT** [comment]
I can't find the iridium folder in the directory usr/lib/python3
![Screenshot 2021-12-08 2 46 pm - I cannot find the iridium folder in python3](https://user-images.githubusercontent.com/81061935/145283306-15d5465b-caa1-49bb-b3b3-61f4cc98f3e4.png)

**Comment by FairyballYT** [comment]
Nevermind, I was searching within the /usr/lib directory, not the usr/local/lib directory
![Uploading Screenshot 2021-12-08 6 45 pm - I found the correct directory where iridium-extractor is installed.png…]()
. 😅

**Comment by FairyballYT** [comment]
I think when I installed the source version of gr-iridium from 3-4 days ago, it got installed to the python3/dist-packages/iridium directory. I'll leave a copy of my installed program if that helps.

Google Drive: https://drive.google.com/file/d/1Twkq0AIjTsqdH8mVjcNssqwzo01gNwqy/view?usp=sharing

**Comment by FairyballYT** [comment]
Whoops, I should've said that DragonOS is based off Debian 20.04, I fixed that in the first comment.

**Comment by schneider42** [comment]
Sorry for not following up here. Are you still experiencing this issue?
